### ISSUE TITLE
Unreliable await message.respond()

### ISSUE THREAD

**Issue by szimszon** [opsdroid/connector-matrix#26]
Hi,

I wonder if you could help me.

I'm writing a shell skill to be able to run shell scripts. I have done this for matrix already but I like this frameworks.
My problem is that sometimes I receive

<pre>Traceback (most recent call last):
  File "/home/szimszon/.opsdroid/modules/opsdroid-modules/skill/shell/__init__.py", line 67, in do_something
    await message.respond(str(stdout))
  File "/usr/local/lib/python3.6/dist-packages/opsdroid/message.py", line 54, in respond
    await self.connector.respond(response)
  File "/home/szimszon/.opsdroid/modules/opsdroid-modules/connector/matrix/connector.py", line 163, in respond
    await self.connection.send_message(room_id, message.text)
  File "/home/szimszon/.opsdroid/modules/opsdroid-modules/connector/matrix/matrix_async.py", line 66, in _send
    async with request as response:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 277, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 624, in start
    (message, payload) = yield from self._protocol.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 554, in read
    yield from self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
</pre>
also the message is not delivered. I don't know the cause for this.
Also if I put the await message.respond() inside a try: except: and resend the message like below it seems to work.

<pre>
           try:
               await message.respond(str(stdout))
            except aiohttp.client_exceptions.ServerDisconnectedError:
               logging.error("stdout: ["+str(stdout)+"]")
               import traceback
               logging.error("Error while sending: "+str(traceback.format_exc()))
               time.sleep(3)
               logging.error("== Retry ==")
               await message.respond(str(stdout))
               logging.error("== Recovered ==")
</pre>

I still get an exception like below between "== Retry ==" and "== Recovered ==" but the message is delivered.
<pre>
ERROR opsdroid-modules.connector.matrix.connector: Matrix Sync Error
Traceback (most recent call last):
  File "/home/szimszon/.opsdroid/modules/opsdroid-modules/connector/matrix/connector.py", line 112, in listen
    filter=self.filter_id)
  File "/home/szimszon/.opsdroid/modules/opsdroid-modules/connector/matrix/matrix_async.py", line 66, in _send
    async with request as response:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 277, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 624, in start
    (message, payload) = yield from self._protocol.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 554, in read
    yield from self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
</pre>

**Comment by szimszon** [comment]
I forgot to mention that I run the shell script with subprocess.Popen and time to time I pull the output and send to the room. It means I don't wait for the exit of the script to provide feedback to the user. And so if I run a script that takes minutes to run I have the output already sent by the script in regular interval.

**Comment by SolarDrew** [comment]
Closed by #28 . Thanks for finding and fixing this, @szimszon :)

**Comment by szimszon** [comment]
Hi,

Thanks for the merge. I wonder still why the **await message.respond()**  is not working first but on the second attempt. Weird...

**Comment by SolarDrew** [comment]
Yeah that does seem odd. I've not had this problem myself, so I wonder if it's an issue with the server rather than the connector, but if this gets around it then whatever, I guess... :man_shrugging:
